version: 0.0
os: linux

files:
  - source: ./
    destination: /home/ubuntu/g90-api-2

hooks:
  ApplicationStop:
    - location: scripts/stop_server.sh
      runas: ubuntu
  BeforeInstall:
    - location: scripts/before_install.sh
      runas: ubuntu
  ApplicationStart:
    - location: scripts/start_server.sh
      runas: ubuntu